---
- name: Install Mysql package
  apt: name={{ item }} state=present update_cache=true
  sudo: true
  with_items:
   - mysql-server
   - python-mysqldb

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/mysql/my.cnf
  notify:
  - restart mysql

- name: Start Mysql Service
  service: name=mysql state=started enabled=yes
