---
- name: Install nginx
  apt: name=nginx state=present update_cache=true

- name: Copy nginx configuration for wordpress
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx
