- hosts: all
  sudo: true
  roles:
    - mysql
    - nginx
    - php-fpm
    - wordpress

  tasks:
    - name: Link /vagrant/ to /srv/wordpress/wp-content/themes/SandersForPresident
      file: name=/srv/wordpress/wp-content/themes/SandersForPresident src=/vagrant state=link

    - name: Install svn
      apt: name=subversion state=present update_cache=true

    - name: Install Advanced Custom Fields plugin
      subversion: repo=http://svn.wp-plugins.org/{{ item.name }}/{{ item.version }}/ dest=/srv/wordpress/wp-content/plugins/{{ item.name }}
      with_items:
        - { name: advanced-custom-fields, version: tags/4.4.1 }
